### ISSUE TITLE
yo angular-2-crud:server => TypeError: Generator.extend is not a function

### ISSUE THREAD

**Issue by xlinx69** [gorums/generator-angular-2-crud#17]
DESCRIPTION
error when running generator to implement server
repetable

ENVIRONNEMENT
node --version
v6.11.1
npm --version
3.10.10
yo --version
2.0.0

OUTPUT
yo angular-2-crud:server
C:\Users\cdena\AppData\Roaming\npm\node_modules\generator-angular-2-crud\generators\server\index.js:9
module.exports = Generator.extend({
                           ^

TypeError: Generator.extend is not a function
    at Object.<anonymous> (C:\Users\cdena\AppData\Roaming\npm\node_modules\generator-angular-2-crud\generators\server\index.js:9:28)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.get [as angular-2-crud:server] (C:\Users\cdena\AppData\Roaming\npm\node_modules\yo\node_modules\yeoman-environment\lib\store.js:38:27)
    at Store.get (C:\Users\cdena\AppData\Roaming\npm\node_modules\yo\node_modules\yeoman-environment\lib\store.js:61:39)

**Comment by nachopavon** [comment]
Same problem here:

node --version
v6.11.3
npm --version
3.10.10
